import { Inter } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
   
   
    <html lang="en">
      
      <body>{children}</body>
      <GoogleTagManager gtmId="GTM-WG3LBJW5" />

    </html>
    </>
  )
}
